version: '3'
services:
  app:
    build: .
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      DATABASE_URL: postgres://user:pass@postgres:5432/db
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run start

  postgres:
    image: postgres:12.4
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
